CREATE TABLE IF NOT EXISTS USER(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	Email VARCHAR(40) NOT NULL,
	Pass VARCHAR(40) NOT NULL,
	Created DATETIME NOT NULL,
	Updated DATETIME NOT NULL, PRIMARY KEY(ID)
);
CREATE TABLE IF NOT EXISTS Categorie(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	Name VARCHAR(40) NOT NULL,
	UserID BIGINT, FOREIGN KEY(UserID) REFERENCES USER(id), PRIMARY KEY(ID)
);
CREATE TABLE IF NOT EXISTS CategorieType(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	Name VARCHAR(50) NOT NULL,
	UserID BIGINT, FOREIGN KEY(UserID) REFERENCES USER(id), PRIMARY KEY(ID)
);
CREATE TABLE IF NOT EXISTS Balance(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	UserID BIGINT,
	CategorieID BIGINT,
	TypeID BIGINT, SUM DECIMAL(10,2), FOREIGN KEY(UserID) REFERENCES USER(id), FOREIGN KEY(CategorieID) REFERENCES Categorie(id), FOREIGN KEY(typeID) REFERENCES CategorieType(id), PRIMARY KEY(ID)
);
